const express = require("express")
const { createuser, verifyEmail, resetOtp, login, addAddress, getMe, logout } = require("../controllers/usercontroller")
const { protect } = require("../middleware/auth")
const Userrouter = express.Router()
Userrouter.post("/create", createuser)
Userrouter.post("/verify-otp", verifyEmail)
Userrouter.post("/reset-otp", resetOtp)
Userrouter.post("/login", login)
Userrouter.get("/get", protect, getMe)
Userrouter.get("/logout", logout)
Userrouter.post("/add-address", protect, addAddress)
module.exports = { Userrouter }